### PR TITLE
Create Kadane'sAlgorithm.cpp

### PR DESCRIPTION
**Pull request by sai-pallavi-2003**

### CODE REVIEW

**Comment by dikshantrajput** [comment]
Please put all these commits in 1 PR.

**Comment by sai-pallavi-2003** [comment]
Should I include multiple programs of the same language in a single PR?

**Comment by dikshantrajput** [comment]
Yes and I am closing the rest of your PRs as of now

**Comment by dikshantrajput** [comment]
Multiple PRs

**Pull request closed without merging**
